### PR TITLE
Upgrade Lodash to v4

### PR DESCRIPTION
**Pull request by nathanstitt**
Continuing the work started at https://github.com/AmpersandJS/ampersand-events/pull/15

I set lodash to `^4.6.1` since that's what the above PR had.

has minimal changes except where needed to reflect the new methods in v4 [changelog](https://github.com/lodash/lodash/wiki/Changelog#v400):
- lodash no longer has `indexBy`, it's been renamed to `keyBy`
- `rest` in v4 has an entirely new & incompatible behaviour.  I substituted `tail` for it and removed `rest`
- `invoke` no longer builds an array of the returned values.  I added `invokeMap` to so that'll still be possible.

Am open to suggestions on adding additional methods if anyone would like 'em.

### CODE REVIEW

**Comment by pgilad** [comment]
You need to camelCase Lodash imports, some OSes are case sensitive

**Comment by klaemo** [comment]
Thank you!
There seem to be some problems with the CI, otherwise this looks good. This would need a semver major release, correct?

**Comment by nathanstitt** [comment]
@pgilad Thanks for pointing out the camelCase issue.  I'm going through the PR's and testing on an Ubuntu VM to make sure I catch them all. 

@klaemo Yes, this one will require a semver major bump.  `rest` has been replaced by `tail` and `indexBy` is now `keyBy`.

**Comment by klaemo** [comment]
@AmpersandJS/community-leaders could anyone set up/fix the sauce labs credentials?

**Comment by klaemo** [comment]
@pgilad do you know how to fix Travis? It complains about missing Saucelabs credentials.

**Comment by klaemo** [comment]
@nathanstitt LGTM. Tests are passing locally. I'm willing to merge it, but would like to get the CI situation sorted out. Thanks for you work :)

**Comment by lukekarrys** [comment]
Closed in favor of #11

**Comment by nathanstitt** [comment]
Why was  #11 chosen? It keeps `rest`, but I think that's a mistake since it's semantics has completely changed. I'd rather have code cause an explicit `method doesn't exist error` rather than a failure in unrelated code when it does something unexpected.  

Wish we'd had some discussion on which approach to choose before merge.

**Comment by lukekarrys** [comment]
I was working in a bunch of repos today and went with all the ones listed in a different issue.

That being said, I didn't look at this one closely enough and I think you're right. Really sorry about that. Since there will be a major version bump anyway (#12) I agree that the old methods should be removed. I'll do that before #12 happens.

Sorry again for the lack of discussion. I had a little time today so I was trying to get All The Lodash Things™️  done today, but ended up rushing a bit.

**Comment by lukekarrys** [comment]
I went ahead and reverted the other one, and merged this instead. Thanks @nathanstitt! While I was typing up that last comment, v3 was published with the previous PR. I'm going to publish v4 now because  of the breaking changes, and chalk v3 up to a failed release on my part.

**Pull request merged**
